### ISSUE TITLE
Hi Dhanesh! 

### ISSUE THREAD

**Issue by blas-asktrady** [blas-asktrady/dummy-repo#1]
Hey @DanexhKum  

My name is Blas and I saw your repos and really liked what you've been working on. I think there's an overlap of interests with what I'm currently building https://asktrady.ai/ 

I would really have the chance to talk to you more about and potentially exchange ideas! 

Looking forward to connect with you,
Blas

PS: Sorry about this informal communication method, but I wasn't sure how else I could contact you lol

**Comment by blas-asktrady** [comment]
@DanexhKum

**Comment by DanexhKum** [comment]
Hello
